name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

env:
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
    CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
    NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
    NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
    MONGO_URI: ${{secrets.MONGO_URI}}
    TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}
    MAILTRAP_USER: ${{secrets.MAILTRAP_USER}}
    MAILTRAP_PASS: ${{secrets.MAILTRAP_PASS}}
    WELCOME_EMAIL_UUID: ${{secrets.WELCOME_EMAIL_UUID}}
    

jobs:
  build:
    name: Build Next.js Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build Next.js
        run: bun run build
